const SIZE_PROPS = {
  xs: [
    'paddingHorizontal',
    'paddingVertical',
    'lineHeight',
    'fontSize',
    'infoTextLineHeight',
    'infoTextFontSize',
    'iconSize',
    'width',
    'height',
    'margin',
  ],
  sm: [
    'paddingHorizontal',
    'paddingVertical',
    'lineHeight',
    'fontSize',
    'infoTextLineHeight',
    'infoTextFontSize',
    'iconSize',
    'width',
    'height',
    'margin',
  ],
  md: [
    'paddingHorizontal',
    'paddingVertical',
    'lineHeight',
    'fontSize',
    'infoTextLineHeight',
    'infoTextFontSize',
    'iconSize',
    'width',
    'height',
    'margin',
  ],
  lg: [
    'paddingHorizontal',
    'paddingVertical',
    'lineHeight',
    'fontSize',
    'infoTextLineHeight',
    'infoTextFontSize',
    'iconSize',
    'width',
    'height',
    'margin',
  ],
  xl: [
    'paddingHorizontal',
    'paddingVertical',
    'lineHeight',
    'fontSize',
    'infoTextLineHeight',
    'infoTextFontSize',
    'iconSize',
    'width',
    'height',
    'margin',
  ],
};

export default SIZE_PROPS;
