const VARIANT_PROPS = {
  primary: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  info: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  success: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  warning: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  danger: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  white: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  black: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  grey: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  lightGrey: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  transparent: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  transparentPrimary: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  transparentDanger: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  transparentWhite: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
  transparentDark: [
    'backgroundColor',
    'color',
    'infoTextColor',
    'borderColor',
    'borderTopColor',
    'borderRightColor',
    'borderBottomColor',
    'borderLeftColor',
  ],
};

export default VARIANT_PROPS;
