const VARIANT_TOKENS = ({theme}) => {
  const {COLORS} = theme.CORE;
  return {
    primary: {
      backgroundColor: COLORS['primary-default'],
      color: COLORS['grey-14'],
      infoTextColor: COLORS['grey-14'],
      borderColor: COLORS['primary-default'],
      borderTopColor: COLORS['primary-default'],
      borderRightColor: COLORS['primary-default'],
      borderBottomColor: COLORS['primary-default'],
      borderLeftColor: COLORS['primary-default'],
    },
    info: {
      backgroundColor: COLORS['info-default'],
      color: '#ffffff',
      infoTextColor: COLORS['info-default'],
      borderColor: COLORS['info-default'],
      borderTopColor: COLORS['info-default'],
      borderRightColor: COLORS['info-default'],
      borderBottomColor: COLORS['info-default'],
      borderLeftColor: COLORS['info-default'],
    },
    success: {
      backgroundColor: COLORS['success-default'],
      color: '#ffffff',
      infoTextColor: COLORS['success-default'],
      borderColor: COLORS['success-default'],
      borderTopColor: COLORS['success-default'],
      borderRightColor: COLORS['success-default'],
      borderBottomColor: COLORS['success-default'],
      borderLeftColor: COLORS['success-default'],
    },
    warning: {
      backgroundColor: COLORS['warning-default'],
      color: '#ffffff',
      infoTextColor: COLORS['warning-default'],
      borderColor: COLORS['warning-default'],
      borderTopColor: COLORS['warning-default'],
      borderRightColor: COLORS['warning-default'],
      borderBottomColor: COLORS['warning-default'],
      borderLeftColor: COLORS['warning-default'],
    },
    danger: {
      backgroundColor: COLORS['danger-default'],
      color: '#ffffff',
      infoTextColor: COLORS['danger-default'],
      borderColor: COLORS['danger-default'],
      borderTopColor: COLORS['danger-default'],
      borderRightColor: COLORS['danger-default'],
      borderBottomColor: COLORS['danger-default'],
      borderLeftColor: COLORS['danger-default'],
    },
    white: {
      backgroundColor: '#ffffff',
      color: COLORS['grey-14'],
      infoTextColor: COLORS['grey-8'],
      borderColor: '#ffffff',
      borderTopColor: '#ffffff',
      borderRightColor: '#ffffff',
      borderBottomColor: '#ffffff',
      borderLeftColor: '#ffffff',
    },
    black: {
      backgroundColor: '#000000',
      color: '#ffffff',
      infoTextColor: '#000000',
      borderColor: '#000000',
      borderTopColor: '#000000',
      borderRightColor: '#000000',
      borderBottomColor: '#000000',
      borderLeftColor: '#000000',
    },
    grey: {
      backgroundColor: COLORS['grey-6'],
      color: '#ffffff',
      infoTextColor: COLORS['grey-6'],
      borderColor: COLORS['grey-6'],
      borderTopColor: COLORS['grey-6'],
      borderRightColor: COLORS['grey-6'],
      borderBottomColor: COLORS['grey-6'],
      borderLeftColor: COLORS['grey-6'],
    },
    lightGrey: {
      backgroundColor: COLORS['grey-2'],
      color: COLORS['grey-16'],
      infoTextColor: COLORS['grey-2'],
      borderColor: COLORS['grey-2'],
      borderTopColor: COLORS['grey-2'],
      borderRightColor: COLORS['grey-2'],
      borderBottomColor: COLORS['grey-2'],
      borderLeftColor: COLORS['grey-2'],
    },
    transparent: {
      backgroundColor: 'transparent',
      color: COLORS['grey-14'],
      infoTextColor: COLORS['grey-8'],
      borderColor: 'transparent',
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
    },
    transparentPrimary: {
      backgroundColor: 'transparent',
      color: COLORS['primary-default'],
      infoTextColor: COLORS['grey-8'],
      borderColor: 'transparent',
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
    },
    transparentDanger: {
      backgroundColor: 'transparent',
      color: COLORS['danger-default'],
      infoTextColor: COLORS['danger-default'],
      borderColor: COLORS['danger-default'],
      borderTopColor: COLORS['danger-default'],
      borderRightColor: COLORS['danger-default'],
      borderBottomColor: COLORS['danger-default'],
      borderLeftColor: COLORS['danger-default'],
    },
    transparentWhite: {
      backgroundColor: 'transparent',
      color: '#ffffff',
      infoTextColor: '#ffffff',
      borderColor: '#ffffff',
      borderTopColor: '#ffffff',
      borderRightColor: '#ffffff',
      borderBottomColor: '#ffffff',
      borderLeftColor: '#ffffff',
    },
    transparentDark: {
      backgroundColor: 'transparent',
      color: COLORS['grey-16'],
      infoTextColor: COLORS['grey-8'],
      borderColor: 'transparent',
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
    },
  };
};

export default VARIANT_TOKENS;
